// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  "apiKey": "mock-api-key",
  "authDomain": "studio-6540754669-81720.firebaseapp.com",
  "projectId": "studio-6540754669-81720",
  "storageBucket": "studio-6540754669-81720.appspot.com",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id"
};
